// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7uOL7trxqoRajtKEJKjKqgVyLpML5r0s',
    appId: '1:408911095395:web:1b5a8a2a260422cb45fa56',
    messagingSenderId: '408911095395',
    projectId: 'instagram-5277a',
    authDomain: 'instagram-5277a.firebaseapp.com',
    storageBucket: 'instagram-5277a.appspot.com',
    measurementId: 'G-XH76PMLPTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6U91C1tnRJZU1kfZ1wh5J8iP_K-MEga0',
    appId: '1:408911095395:android:f8b18eb4f28b928c45fa56',
    messagingSenderId: '408911095395',
    projectId: 'instagram-5277a',
    storageBucket: 'instagram-5277a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVOjFyjNcz2MhLtMadru_JFL6huDcHJ34',
    appId: '1:408911095395:ios:829e1ba3d3607e9c45fa56',
    messagingSenderId: '408911095395',
    projectId: 'instagram-5277a',
    storageBucket: 'instagram-5277a.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7uOL7trxqoRajtKEJKjKqgVyLpML5r0s',
    appId: '1:408911095395:web:5e959073ffd0ceb545fa56',
    messagingSenderId: '408911095395',
    projectId: 'instagram-5277a',
    authDomain: 'instagram-5277a.firebaseapp.com',
    storageBucket: 'instagram-5277a.appspot.com',
    measurementId: 'G-ZJGY4G8YV5',
  );
}
